/**
 * hodor docs worker — static site + catalog search.
 *
 * Static assets live in `./public` and are served asset-first (fallback in
 * `app.notFound`). Two worker routes run first:
 *
 *   GET /catalog        → the catalog page (catalog.html, served from assets)
 *   GET /catalog/search → server-side search over the build-time catalog
 *                         snapshot (`public/catalog.json`, bundled at deploy)
 *
 * The snapshot is generated by `scripts/snapshot-catalog.mjs` before every
 * dev/build/deploy, so the catalog never depends on the GitHub raw URL at
 * runtime.
 */

import { Hono } from "hono";
import snapshot from "../public/catalog.json";

type Env = { assets: { fetch: (input: Request) => Promise<Response> } };

const MAX_RESULTS = 100;

const app = new Hono<{ Bindings: Env }>();

/**
 * Rank an item for a query (lower is better). -1 = no match.
 * Prefix hits beat substring hits; id beats label beats description beats host.
 */
function score(item: (typeof snapshot.items)[number], q: string): number {
  if (q === "") return 0;
  if (item.id.startsWith(q)) return 0;
  if (item.id.includes(q)) return 1;
  if (item.label.toLowerCase().includes(q)) return 2;
  if (item.description.toLowerCase().includes(q)) return 3;
  if (item.host.includes(q)) return 4;
  return -1;
}

app.get("/catalog", (c) => c.env.assets.fetch(new Request("https://x/catalog.html")));

app.get("/catalog/search", (c) => {
  const raw = c.req.query("q") ?? "";
  const q = raw.trim().toLowerCase();
  const items = snapshot.items
    .map((item) => ({ item, s: score(item, q) }))
    .filter(({ s }) => s >= 0)
    .sort((a, b) => a.s - b.s || a.item.id.localeCompare(b.item.id))
    .slice(0, MAX_RESULTS)
    .map(({ item }) => item);
  return c.json({ query: raw, count: snapshot.count, total: items.length, items });
});

app.notFound((c) => c.env.assets.fetch(c.req.raw));

export default app;
