/**
 * Single-version sync (the app version, not the per-deploy Cloudflare version).
 *
 * Root `package.json` "version" is the ONLY maintained value. This stamps it
 * onto every worker's `package.json` and generates `src/version.ts` for the
 * proxy (exposed at runtime via `/_/admin/info`). The docs catalog snapshot
 * reads the root version directly — no copies, nothing hand-edited:
 *
 *   pnpm version 0.2.0   # or edit root package.json
 *   pnpm version:sync    # stamp workers + generate src/version.ts
 *
 * @module
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const rootPkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = rootPkg.version;
if (!version) throw new Error("root package.json has no version");

const targets = ["apps/proxy-worker/package.json", "apps/docs-worker/package.json"];
for (const rel of targets) {
  const path = join(root, rel);
  const pkg = JSON.parse(readFileSync(path, "utf8"));
  pkg.version = version;
  writeFileSync(path, JSON.stringify(pkg, null, 2) + "\n");
  console.log(`version ${version} -> ${rel}`);
}

const versionTs = `/**
 * Generated by scripts/sync-version.mjs from root package.json — do not edit.
 * Exposed at runtime via /_/admin/info.
 */
export const APP_VERSION = "${version}";
`;
writeFileSync(join(root, "apps/proxy-worker/src/version.ts"), versionTs);
console.log(`version ${version} -> apps/proxy-worker/src/version.ts`);
